version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: aks-coach
    main: ./cmd/aks-coach
    binary: aks-coach
    ldflags:
      - -s -w
      - -X aks-coach/internal/version.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: []

archives:
  - id: archive
    builds: [aks-coach]
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - completions/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: git

release:
  prerelease: "auto"
  draft: false
